### ISSUE TITLE
ios support?

### ISSUE THREAD

**Issue by Ehco1996** [purkylin/proxy-nio#1]
hi, i am curious about how to run this proxy on ios?

**Comment by purkylin** [comment]
it's in plan. I am in refactoring currently. But in iOS platform the UDP packet maybe not be processed.

**Comment by Ehco1996** [comment]
thanks to reply , i will keep watching this project :)

**Comment by Ehco1996** [comment]
@purkylin  which ui framework you want to use ? would you consider about SwiftUI?

**Comment by purkylin** [comment]
It has no UI, just an Infrastructure framework. 
I prefer SwiftUI to build a new app.
